# Questions for section 1

**Table of contents**<a id='toc0_'></a>    
- 1. [Augmentation operators (`+=`, `*=`, etc.)](#toc1_)    
- 2. [Is the final exam more difficult than the problem set?](#toc2_)    
- 3. [Choosing an optimizer](#toc3_)    
- 4. [Separate py-files](#toc4_)    
- 5. [How to tackle the projects (and copying codes from the lecture notebooks)](#toc5_)    
- 6. [Time of day of the deadline](#toc6_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

Answer to the questions you had in the survey.

## 1. <a id='toc1_'></a>[Augmentation operators (`+=`, `*=`, etc.)](#toc0_)

Augmentation operators augment the original variable with some operator (`+`, `*` etc). <br>
Meaning they change the value of the variable by performing some operation on the original value. <br>
The main purpose is to have shorter syntax.

In [10]:
# Comparing regular syntax (i) with the augmentation (j):
i = 1 
j = 1
print(i,j)
i = i +1
j += j  # The exact same as the line above, just using augmentation
print(i,j)
i = i*4
j *= 4 
print(i,j)
i = i-2
j -= 2
print(i,j)
i = i/2
j /= 2
print(i,j)

1 1
2 2
8 8
6 6
3.0 3.0


### Numpy arrays

An exception is **numpy arrays**. Here the augmentation operator can imply different behavior, when the array is a view.

In [2]:
import numpy as np

In [3]:
A = np.array([1,2,3])
B = A[0] # copies the first row of A
B += 1 # updates B
print(A) # is not affected

[1 2 3]


In [4]:
A = np.array([1,2,3])
B = A[0:] # construct a view into the first row of A
B += 1 # updates B and therefore A
print(A) # is affected

[2 3 4]


In [5]:
A = np.array([1,2,3])
B = A[0:] # construct a view into the row
B = B + 1 # creates a new B
print(A) # is not affected

[1 2 3]


## 2. <a id='toc2_'></a>[Is the final exam more difficult than the problem set?](#toc0_)

The final exam will not be much more difficult than the problem sets in terms of the material. The main difference is that there is no solution guide and it will be less clear which lectures you should look to for help. This will make it much more likely that there will be times where you are stuck and don't know what to do. <br> 
The inaugural project is a good indicator for the level of dificulty and how much help the problem description will give you. <br>
You can see previous exams at the [github repository](https://github.com/NumEconCopenhagen/IntroProg-lectures/tree/main/exams) 

## 3. <a id='toc3_'></a>[Choosing an optimizer](#toc0_)

You'll learn more about this later in the course. <br>
Generally, I would use `Nelder-Mead` if speed is not an issue. It is robust (to 'jumpy' functions) and can handle bounds (but not constraints). <br>
If you need constrainted optimization I would recommend `SLSQP`. <br>
Later you will learn about gradient based optimization (`Newton-CG` and `BFGS`) which are faster if the function is nice (approximately continous and differentiable). 

Numerical optimization is not an exact science, and when dealing with complex problems, you can run into local maximums. So experimentaion is encouraged! <br>
If different optimizers and starting values give the same result, you can just use the fastest. If they give different results, use the optimizer that finds the best optimium, and use multiple starting values to ensure that you've found the best optimium.

For anyone who is interested, I've attached the pdf, *noteOptimization*, written by Anders Munk-Nielsen. It explains what is happening under the hood of some these methods and also has a guide for troupleshooting.

## 4. <a id='toc4_'></a>[Separate py-files](#toc0_)

There was a question about whether it was always better to use a seperate py-file when using functions. <br>
My answer is yes (except for very small projects). <br>
Writing a lot code in notebooks, quickly gets very cluttered and unorganized.
Notebooks are great at showing the results of code and explaining what you've done, but solving big problems requires many lines of code, and that is simply easier to organize in a py-file.

## 5. <a id='toc5_'></a>[How to tackle the projects (and copying codes from the lecture notebooks)](#toc0_)

* Listen today 
* Spend time fully understanding what you are asked to do
* Try to pin point if code from the lectures and problem sets can help you (the plot lecture and the optimization lecture for example).
* Solving the problems will be a mixture of coming up with your own code and copying relevant code and editing it, such that it fits you specific problem. <br> 
I want to emphasize that it is allowed to copy code from the course material and adjust it to your problem.
* Start by making it work first, then make it look better/run faster and so on.
* But document what you do while you are doing it, you will love yourself for doing this when you have to edit the code later.

## 6. <a id='toc6_'></a>[Time of day of the deadline](#toc0_)

The deadline is at the end of the day (23:59).

You are also very welcome to ask a question about anything by raising an issue on [github](https://github.com/NumEconCopenhagen/IntroProg-lectures/issues) <br>
(I know *raising an issue* sounds harsh but that's just wording) <br>
This is a really good way of asking questions because they are public (so it can help other people), it is easy to write code, and we can easily find you own project repositories and see directly what you have done.